# Multiclass SVM 구현

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score

#IRIS 데이터 로드
iris =  sns.load_dataset('iris') 
X= iris.iloc[:,:4] #학습할데이터
y = iris.iloc[:,-1] #타겟
print(y)

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...    
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: species, Length: 150, dtype: object


In [2]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=48)

In [3]:
def standardization(train, test):
    scaler = StandardScaler()
    train = scaler.fit_transform(train)
    test = scaler.transform(test)
    return train, test

X_train, X_test = standardization(X_train, X_test)

In [4]:
X_train

array([[ 0.78522493,  0.32015325,  0.77221097,  1.04726529],
       [-0.26563371, -1.29989934,  0.0982814 , -0.11996537],
       [ 0.43493872,  0.78302542,  0.94069336,  1.43634218],
       [-0.84944407,  0.78302542, -1.24957775, -1.28719604],
       [-0.38239578, -1.7627715 ,  0.15444219,  0.13941922],
       [ 0.55170079, -0.374155  ,  1.05301496,  0.7878807 ],
       [ 0.31817664, -0.14271892,  0.65988937,  0.7878807 ],
       [ 0.20141457, -0.374155  ,  0.43524618,  0.39880381],
       [-1.66677857, -0.14271892, -1.36189934, -1.28719604],
       [-0.14887164, -0.60559109,  0.21060299,  0.13941922],
       [-0.14887164, -1.06846325, -0.12636179, -0.24965767],
       [ 0.31817664, -0.60559109,  0.15444219,  0.13941922],
       [ 0.66846286, -0.83702717,  0.88453256,  0.91757299],
       [ 0.0846525 , -0.14271892,  0.77221097,  0.7878807 ],
       [-0.49915786, -0.14271892,  0.43524618,  0.39880381],
       [-0.26563371, -0.60559109,  0.65988937,  1.04726529],
       [ 2.18636979,  1.

In [5]:
X_test

array([[-0.14887164, -0.374155  ,  0.26676379,  0.13941922],
       [ 0.31817664, -0.60559109,  0.54756778,  0.00972692],
       [ 0.31817664, -1.06846325,  1.05301496,  0.26911151],
       [-1.5500165 , -1.7627715 , -1.36189934, -1.15750374],
       [ 0.0846525 ,  0.32015325,  0.60372857,  0.7878807 ],
       [ 0.78522493, -0.14271892,  0.99685416,  0.7878807 ],
       [-0.84944407,  1.70876975, -1.24957775, -1.15750374],
       [ 0.20141457, -0.14271892,  0.60372857,  0.7878807 ],
       [-0.38239578,  2.63451409, -1.30573855, -1.28719604],
       [-0.38239578, -1.29989934,  0.15444219,  0.13941922],
       [ 0.66846286,  0.08871717,  0.99685416,  0.7878807 ],
       [-0.38239578,  1.0144615 , -1.36189934, -1.28719604],
       [-0.49915786,  0.78302542, -1.13725615, -1.28719604],
       [ 0.43493872, -0.60559109,  0.60372857,  0.7878807 ],
       [ 0.55170079, -1.7627715 ,  0.37908538,  0.13941922],
       [ 0.55170079,  0.55158933,  0.54756778,  0.52849611],
       [-1.19973028,  0.

In [10]:
sety_train = y_train.replace(["setosa","versicolor","virginica"],[1,0,0])
very_train = y_train.replace(["setosa","versicolor","virginica"],[0,1,0])
viry_train = y_train.replace(["setosa","versicolor","virginica"],[0,0,1])

In [16]:
sety_svm = SVC(probability=True)
sety_svm.fit(X_train,sety_train)

SVC(probability=True)

In [17]:
sety_svm.predict_proba(X_test)

array([[0.9880477 , 0.0119523 ],
       [0.9894721 , 0.0105279 ],
       [0.98865944, 0.01134056],
       [0.64111312, 0.35888688],
       [0.98976816, 0.01023184],
       [0.99186674, 0.00813326],
       [0.02305355, 0.97694645],
       [0.992405  , 0.007595  ],
       [0.02974457, 0.97025543],
       [0.99276109, 0.00723891],
       [0.99181291, 0.00818709],
       [0.0216192 , 0.9783808 ],
       [0.02293314, 0.97706686],
       [0.99254206, 0.00745794],
       [0.9839051 , 0.0160949 ],
       [0.98799151, 0.01200849],
       [0.0160428 , 0.9839572 ],
       [0.98246004, 0.01753996],
       [0.98907693, 0.01092307],
       [0.98906922, 0.01093078],
       [0.0488009 , 0.9511991 ],
       [0.9916033 , 0.0083967 ],
       [0.99123713, 0.00876287],
       [0.98895533, 0.01104467],
       [0.98816381, 0.01183619],
       [0.01718719, 0.98281281],
       [0.02728571, 0.97271429],
       [0.98309077, 0.01690923],
       [0.98813776, 0.01186224],
       [0.98239258, 0.01760742]])

In [37]:
very_svm = SVC(probability=True)
very_svm.fit(X_train,very_train)
very_svm.predict_proba(X_test)

viry_svm = SVC(probability=True)
viry_svm.fit(X_train,viry_train)
viry_svm.predict_proba(X_test)

array([[9.92586745e-01, 7.41325498e-03],
       [9.84410717e-01, 1.55892831e-02],
       [3.27637555e-01, 6.72362445e-01],
       [9.57666046e-01, 4.23339536e-02],
       [5.80055683e-01, 4.19944317e-01],
       [5.22140995e-02, 9.47785901e-01],
       [9.82526362e-01, 1.74736376e-02],
       [3.05330820e-01, 6.94669180e-01],
       [9.70861788e-01, 2.91382118e-02],
       [9.66247482e-01, 3.37525179e-02],
       [7.84836858e-02, 9.21516314e-01],
       [9.89642803e-01, 1.03571968e-02],
       [9.94075543e-01, 5.92445682e-03],
       [1.42655638e-01, 8.57344362e-01],
       [8.98245819e-01, 1.01754181e-01],
       [9.09911294e-01, 9.00887058e-02],
       [9.86982662e-01, 1.30173376e-02],
       [9.81981858e-01, 1.80181419e-02],
       [4.94128020e-01, 5.05871980e-01],
       [3.65672131e-03, 9.96343279e-01],
       [9.78052357e-01, 2.19476432e-02],
       [2.10156874e-02, 9.78984313e-01],
       [3.56430764e-01, 6.43569236e-01],
       [9.13886405e-01, 8.61135949e-02],
       [1.635492

In [39]:
last = np.c_[sety_svm.predict_proba(X_test)[:,1],
      very_svm.predict_proba(X_test)[:,1],
     viry_svm.predict_proba(X_test)[:,1]]
               

In [47]:
pd.DataFrame(last).apply(lambda x : np.argmax(x),axis=1).replace(
    [0,1,2],["setosa","versicolor","virginica"])

0     versicolor
1     versicolor
2      virginica
3         setosa
4     versicolor
5      virginica
6         setosa
7      virginica
8         setosa
9     versicolor
10     virginica
11        setosa
12        setosa
13     virginica
14    versicolor
15    versicolor
16        setosa
17    versicolor
18     virginica
19     virginica
20        setosa
21     virginica
22     virginica
23    versicolor
24     virginica
25        setosa
26        setosa
27     virginica
28     virginica
29    versicolor
dtype: object

In [53]:
def MultipleSVM(X,y) :
    
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=48)
    
    X_train, X_test = standardization(X_train, X_test)
    
    zerolist = [0]*len(y.unique())
    
    for num, i in enumerate(y.unique()):
        
        zerolist[num] = 1
        y_train_rest = y_train.replace(y.unique(),zerolist)
        svm = SVC(probability=True)
        svm.fit(X_train,y_train_rest)
        
        if num == 0 :
            last = svm.predict_proba(X_test)[:,1]
            
        else :
            last = np.c_[last, svm.predict_proba(X_test)[:,1]]
            
        zerolist[num] = 0
        
    return (pd.DataFrame(last).apply(lambda x : np.argmax(x),axis=1).replace(
    [k for k in range(len(y.unique()))],y.unique())
           )
        
        

In [54]:
MultipleSVM(X,y)

0     versicolor
1     versicolor
2      virginica
3         setosa
4     versicolor
5      virginica
6         setosa
7      virginica
8         setosa
9     versicolor
10     virginica
11        setosa
12        setosa
13     virginica
14    versicolor
15    versicolor
16        setosa
17    versicolor
18     virginica
19     virginica
20        setosa
21     virginica
22     virginica
23    versicolor
24     virginica
25        setosa
26        setosa
27     virginica
28     virginica
29    versicolor
dtype: object